package com.olacabs.play.repo.db;

import com.olacabs.play.repo.db.db_utils.OlaPlayDatabase;
import com.olacabs.play.repo.model.Music;

import java.util.List;

import javax.inject.Inject;
import javax.inject.Singleton;

import io.reactivex.Observable;

/**
 * Generated by Dipendra on 16/12/17
 */

@Singleton
public class DBHelper implements IDBHelper {

    private final OlaPlayDatabase mAppDatabase;

    @Inject
    public DBHelper(OlaPlayDatabase mAppDatabase) {
        this.mAppDatabase = mAppDatabase;
    }

    @Override
    public Observable<List<Music>> getAllMusic() {
        return Observable.fromCallable(() -> mAppDatabase.musicDAO().loadAll());
    }

    @Override
    public Observable<Boolean> isMusicEmpty() {
        return Observable.fromCallable(() -> mAppDatabase.musicDAO().loadAll().isEmpty());
    }

    @Override
    public boolean saveMusic(Music music) {
         mAppDatabase.musicDAO().insert(music);
        return true;
    }

    @Override
    public boolean saveMusicList(List<Music> musicList) {
        mAppDatabase.musicDAO().insertAll(musicList);
        return true;
    }
}
