package com.olacabs.play.repo.dir;

import javax.inject.Inject;
import javax.inject.Singleton;

/**
 * Generated by Dipendra on 16/12/17
 */

@Singleton
public class FileHelper implements IFileHelper {

    @Inject
    public FileHelper() {
    }
}
