package com.olacabs.play.ui.base;

import android.support.v7.widget.RecyclerView;
import android.view.View;

/**
 * Generated by Dipendra on 16/12/17
 */

public abstract class BaseViewHolder extends RecyclerView.ViewHolder {

    public BaseViewHolder(View itemView) {
        super(itemView);
    }

    public abstract void onBind(int position);

}
