package com.olacabs.play.di;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

import javax.inject.Qualifier;

/**
 * Generated by Dipendra on 16/12/17
 */

@Qualifier
@Retention(RetentionPolicy.RUNTIME)
public @interface FileInfo {
}
