package com.olacabs.play.ui.list;

import com.olacabs.play.repo.IDataManager;
import com.olacabs.play.utils.rx.ISchedulerProvider;

import dagger.Module;
import dagger.Provides;

/**
 * Generated by Dipendra on 16-12-2017.
 */
@Module
public class ListActivityModule {

    @Provides
    ListViewModel provideListViewModel(IDataManager dataManager,
                                       ISchedulerProvider schedulerProvider) {
        return new ListViewModel(dataManager, schedulerProvider);
    }
}
