package com.olacabs.play.repo.db.db_utils;

import android.arch.persistence.room.Database;
import android.arch.persistence.room.RoomDatabase;

import com.olacabs.play.repo.model.Music;

/**
 * Generated by Dipendra on 08/11/17 - 12:11 PM
 */

@Database(entities = {Music.class}, version = 1, exportSchema = false)
public abstract class OlaPlayDatabase extends RoomDatabase {

    public abstract MusicDAO musicDAO();

}