package com.olacabs.play.repo.api;

import com.olacabs.play.repo.model.Music;

import java.util.List;

import io.reactivex.Observable;

/**
 * Generated by Dipendra on 16/12/17
 */

public interface IRestApiHelper {

    Observable<List<Music>> getMusicList();
}
