package com.olacabs.play.repo.api;

import android.databinding.ObservableList;

import com.olacabs.play.repo.model.Music;
import com.olacabs.play.utils.Constants;
import com.rx2androidnetworking.Rx2AndroidNetworking;

import java.util.List;

import javax.inject.Inject;
import javax.inject.Singleton;

import io.reactivex.Observable;

/**
 * Generated by Dipendra on 16/12/17
 */

@Singleton
public class RestApiHelper implements IRestApiHelper {

    @Inject
    public RestApiHelper() {
    }

    @Override
    public Observable<List<Music>> getMusicList() {
        return Rx2AndroidNetworking.get(Constants.BASE_URL)
                .build().getObjectListObservable(Music.class);
    }

}
