package com.olacabs.play.repo;

import com.olacabs.play.repo.api.IRestApiHelper;
import com.olacabs.play.repo.db.IDBHelper;
import com.olacabs.play.repo.dir.IFileHelper;
import com.olacabs.play.repo.pref.IPreferenceHelper;

import io.reactivex.Observable;


/**
 * Generated by Dipendra on 16/12/17
 */

public interface IDataManager extends IDBHelper, IFileHelper, IRestApiHelper, IPreferenceHelper {

}
