package com.olacabs.play.ui.splash;


import com.olacabs.play.repo.IDataManager;
import com.olacabs.play.utils.rx.ISchedulerProvider;

import dagger.Module;
import dagger.Provides;

/**
 * Generated by Dipendra on 16/12/17
 */

@Module
public class SplashActivityModule {

    @Provides
    SplashViewModel provideSplashViewModel(IDataManager dataManager,
                                           ISchedulerProvider schedulerProvider) {
        return new SplashViewModel(dataManager, schedulerProvider);
    }

}
