package com.olacabs.play.ui.splash;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;

import com.olacabs.play.BR;
import com.olacabs.play.R;
import com.olacabs.play.databinding.ActivitySplashBinding;
import com.olacabs.play.ui.base.BaseActivity;
import com.olacabs.play.ui.list.ListActivity;
import com.olacabs.play.utils.ViewUtils;

import javax.inject.Inject;

/**
 * Generated by Dipendra on 16/12/17
 */

public class SplashActivity extends BaseActivity<ActivitySplashBinding, SplashViewModel>
        implements ISplashNavigator {

    @Inject
    SplashViewModel mSplashViewModel;

    @Inject
    ViewUtils customAnimation;

    private ActivitySplashBinding activitySplashBinding;

    public static Intent getStartIntent(Context context) {
        Intent intent = new Intent(context, SplashActivity.class);
        return intent;
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        //noinspection ConstantConditions
        getSupportActionBar().hide();
        mSplashViewModel.setNavigator(this);
        activitySplashBinding = getViewDataBinding();
        mSplashViewModel.waitOnScreen();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
    }


    @Override
    public void openMainActivity() {
        startActivity(ListActivity.getStartIntent(this));
    }

    @Override
    public SplashViewModel getViewModel() {
        return mSplashViewModel;
    }

    @Override
    public int getBindingVariable() {
        return BR.viewModel;
    }

    @Override
    public int getLayoutId() {
        return R.layout.activity_splash;
    }
}