package com.olacabs.play.repo.pref;

/**
 * Generated by Dipendra on 06-11-2017 - 10:56 AM
 */


public interface IPreferenceHelper {

    boolean isMusicDownloaded();

    void setMusicDownloaded(boolean isMusicDownloaded);
}
