package com.olacabs.play.repo.pref;

import android.content.Context;
import android.content.SharedPreferences;

import com.olacabs.play.di.PreferenceInfo;

import javax.inject.Inject;
import javax.inject.Singleton;


/**
 * Generated by Dipendra on 16/12/17
 */

@Singleton
public class PreferenceHelper implements IPreferenceHelper {

    private final SharedPreferences mPrefs;

    @Inject
    public PreferenceHelper(Context context,
                            @PreferenceInfo String prefFileName) {
        mPrefs = context.getSharedPreferences(prefFileName, Context.MODE_PRIVATE);
    }

    @Override
    public boolean isMusicDownloaded() {
        return mPrefs.getBoolean("isMusicDownloaded", false);
    }

    @Override
    public void setMusicDownloaded(boolean isMusicDownloaded) {
        mPrefs.edit().putBoolean("isMusicDownloaded", isMusicDownloaded).apply();
    }

}
