package com.olacabs.play.utils.rx;

import io.reactivex.Scheduler;

/**
 * Generated by Dipendra on 16/12/17
 */

public interface ISchedulerProvider {

    Scheduler ui();

    Scheduler computation();

    Scheduler io();

}
