package com.olacabs.play.utils;

/**
 * Generated by Dipendra on 16/12/17
 */

public class Constants {

    public static final String DB_NAME = "ola_play.db";
    public static final String PREF_NAME = "ola_play";
    public static final String TIMESTAMP_FORMAT = "yyyyMMdd_HHmmss";
    public static final String BASE_URL = "http://starlord.hackerearth.com/studio";

    public static Long TIMER_VALUE = 2L;
}