package com.olacabs.play.di.builder;

import com.olacabs.play.ui.list.ListActivity;
import com.olacabs.play.ui.list.ListActivityModule;
import com.olacabs.play.ui.list.music.MusicFragmentProvider;
import com.olacabs.play.ui.splash.SplashActivity;
import com.olacabs.play.ui.splash.SplashActivityModule;

import dagger.Module;
import dagger.android.ContributesAndroidInjector;

/**
 * Generated by Dipendra on 16/12/17
 */

@Module
public abstract class ActivityBuilder {

    @ContributesAndroidInjector(modules = SplashActivityModule.class)
    abstract SplashActivity bindSplashActivity();

    @ContributesAndroidInjector(modules = {ListActivityModule.class, MusicFragmentProvider.class})
    abstract ListActivity bindListActivity();

}
